//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEA_Salón.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cierre
    {
        public int IdCierre { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public double EfectivoInicial { get; set; }
        public double TotalVenta { get; set; }
        public double TotalEfectivo { get; set; }
        public Nullable<double> EfectivoSobrante { get; set; }
        public Nullable<double> EfectivoFaltante { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
