//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEA_Salón.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Compra
    {
        [Key]
        public int IdCompra { get; set; }
        [Display(Name = "Producto")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        public Nullable<int> IdProducto { get; set; }

        public Nullable<int> IdProveedor { get; set; }
        [Display(Name = "Precio")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        public double PrecioCompra { get; set; }

        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        public Nullable<int> Cantidad { get; set; }

        [Display(Name = "Fecha Vencimiento")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaVencimiento { get; set; }

        [Display(Name = "Fecha Compra")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCompra { get; set; }

        public bool Estado { get; set; }

        public Nullable<double> TotalCompra { get; set; }
        [Display(Name = "Precio Venta")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        public Nullable<double> PrecioVenta { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
