//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEA_Salón.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Compra = new HashSet<Compra>();
        }

        [Key]
        public int IdProveedor { get; set; }

        [Display(Name = "Proveedor")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        [StringLength(50, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 3)]
        public string NombreProveedor { get; set; }
        [Display(Name = "Empresa")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        [StringLength(50, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 0)]
        public string NombreEmplesa { get; set; }
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Campo {0}, Es Requerido")]
        [StringLength(9, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 3)]
        public string Telefono { get; set; }
        [Display(Name = "Proveedor")]
        [StringLength(100, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 0)]
        public string Direccion { get; set; }
        public bool Estado { get; set; }
        [Display(Name = "Email")]
        [StringLength(50, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 0)]
        public string Email { get; set; }
        [Display(Name = "DUI")]
        [StringLength(10, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 0)]
        public string DUI { get; set; }
        [Display(Name = "N° Contribuyente")]
        [StringLength(50, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 0)]
        public string NCR { get; set; }
        [Display(Name = "Proveedor")]
        [StringLength(17, ErrorMessage = "Campo {0}, puede contener maximo {1} y minimo {2} Digitos ", MinimumLength = 0)]
        public string NIT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}
